#!/usr/bin/env bash
# install-vault-hooks.sh — idempotently install the lore pre-commit status guard
# into a vault's .git/hooks/pre-commit.
#
# Usage: install-vault-hooks.sh <vault-path>
#
# Requires LORE_PLUGIN_ROOT to be set (pointing at the plugins/lore/ dir of the
# installed lore plugin). `lore init` sets this automatically.
#
# Chain-safety: if .git/hooks/pre-commit already exists and is not our wrapper,
# we emit a wrapper that runs the original hook first, then our guard. The
# original hook is preserved byte-for-byte; we never clobber it silently.
#
# Idempotent: re-running when our wrapper is already in place is a no-op.

set -euo pipefail

VAULT="${1:-}"
if [ -z "$VAULT" ]; then
    echo "usage: install-vault-hooks.sh <vault-path>" >&2
    exit 1
fi

VAULT="$(cd "$VAULT" && pwd)"
GIT_HOOKS_DIR="$VAULT/.git/hooks"
TARGET="$GIT_HOOKS_DIR/pre-commit"

if [ ! -d "$GIT_HOOKS_DIR" ]; then
    echo "error: .git/hooks not found at $GIT_HOOKS_DIR — is $VAULT a git repo?" >&2
    exit 1
fi

if [ -z "${LORE_PLUGIN_ROOT:-}" ]; then
    echo "error: LORE_PLUGIN_ROOT is not set. Set it to the lore plugin directory." >&2
    exit 1
fi

GUARD_SH="$LORE_PLUGIN_ROOT/hooks/pre-commit-status-guard.sh"
if [ ! -f "$GUARD_SH" ]; then
    echo "error: lore guard not found at $GUARD_SH" >&2
    exit 1
fi

# Idempotent marker embedded in the wrapper we write.
MARKER="# lore-status-guard-installed"

# Already installed by us?
if [ -f "$TARGET" ] && grep -qF "$MARKER" "$TARGET" 2>/dev/null; then
    echo "lore pre-commit guard already installed at $TARGET"
    exit 0
fi

if [ -e "$TARGET" ]; then
    # Something else is already there — chain-safe mode: save original, then
    # build a wrapper that runs original first, then our guard.
    ORIGINAL_HOOK="$GIT_HOOKS_DIR/pre-commit-before-lore"
    cp "$TARGET" "$ORIGINAL_HOOK"
    chmod +x "$ORIGINAL_HOOK"
    echo "lore: existing pre-commit hook saved to $ORIGINAL_HOOK"

    cat > "$TARGET" <<EOF
#!/usr/bin/env bash
$MARKER
# Chain: run the original pre-commit hook, then the lore status guard.
# Original hook was saved to $ORIGINAL_HOOK at install time.

set -euo pipefail

# Run original hook first.
"$ORIGINAL_HOOK" "\$@" || exit \$?

# Run lore status guard.
export LORE_GUARD_STRICT=1
export LORE_PLUGIN_ROOT="$LORE_PLUGIN_ROOT"
exec "$GUARD_SH" "\$@"
EOF
else
    cat > "$TARGET" <<EOF
#!/usr/bin/env bash
$MARKER
# Lore pre-commit status guard.
# Validates staged .md files have canonical status: values.
# Generated by install-vault-hooks.sh — do not edit this header.

set -euo pipefail

export LORE_GUARD_STRICT=1
export LORE_PLUGIN_ROOT="$LORE_PLUGIN_ROOT"
exec "$GUARD_SH" "\$@"
EOF
fi

chmod +x "$TARGET"
echo "Installed lore pre-commit guard at $TARGET"
